HospiceNiagara/Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HospiceNiagara.Models
{
    public class Schedule
    {
        

        public int ID { get; set; }

        public string Category { get; set; }

        public string Month { get; set; }

        public int Year { get; set; }

        public bool IsActiveSchedule { get; set; }

        public DateTime DataAdded { get; set; }

        [DisplayName("Resource")]
        public int ResourceID { get; set; }
        public Resource Resource { get; set; }

    }
}

HospiceNiagara/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospiceNiagara.DAL;
using HospiceNiagara.Models;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;
using System.Globalization;
using HospiceNiagara.HospiceUserExtensions;
namespace HospiceNiagara.Controllers
{
    [Authorize]
    public class SchedulesController : Controller
    {
        private HospiceNiagaraContext db = new HospiceNiagaraContext();
        enum getmonths { January, February, March, April, May, June, July, August, September, October, November, December };
        // GET: Schedules
        [SessionTracking.Logging]
        public ActionResult Index()
        {
            
            
            //string m = CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(DateTime.Now.Month);
            var schedules = db.Schedules.Include(s => s.Resource);
           
            
            
            List<Schedule> res = schedules.Where(s => s.Category == "Residential Schedule" & s.IsActiveSchedule == true).ToList();
            List<Schedule> pet = schedules.Where(s => s.Category == "Pet Therapy Schedule" & s.IsActiveSchedule == true).ToList();
            List<Schedule> day = schedules.Where(s => s.Category == "Welland Day Hospice Schedule" & s.IsActiveSchedule == true).ToList();
            List<Schedule> events = schedules.Where(s => s.Category == "Event Schedule" & s.IsActiveSchedule == true).ToList();
            
            ViewBag.ResidentialDD = ActiveSchedDropDown(res);
            ViewBag.PetDD = ActiveSchedDropDown(pet);
            ViewBag.DayDD = ActiveSchedDropDown(day);
            ViewBag.EventDD = ActiveSchedDropDown(events);
                           return View(schedules.ToList());
            
           
            
        }
        [Authorize(Roles="CantGetHere")]
        public ActionResult GoodIndex()
        {
            var schedules = db.Schedules.Include(s => s.Resource);
            var res = schedules.Where(s => s.Category == "Residential Schedule" & s.IsActiveSchedule == true);
            var pet = schedules.Where(s => s.Category == "Pet Therapy Schedule" & s.IsActiveSchedule == true);
            var day = schedules.Where(s => s.Category == "Welland Day Hospice Schedule" & s.IsActiveSchedule == true);
            var events = schedules.Where(s => s.Category == "Event Schedule" & s.IsActiveSchedule == true);

            ViewBag.ResidentialDD = new SelectList(res, "ResourceID", "Month", "Select a Month");

            return View(schedules.ToList());
        }
       
        public ActionResult ShowSched(int id)
        {

            var fileTitle = db.Resources.Where(u => u.FileStoreID == id).SingleOrDefault();
            ViewBag.Title = fileTitle.FileDesc;
            var theFile = db.FileStores.Where(f => f.ID == id).SingleOrDefault();
            var length = theFile.FileContent.Length;

            string string64 = Convert.ToBase64String(theFile.FileContent);
            ViewBag.Mime = theFile.MimeType;
            ViewBag.Name = theFile.FileName;
            ViewBag.FileBits = string64;
            return PartialView("ShowSched");
        }



        // GET: Schedules/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // GET: Schedules/Create
         [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            if (TempData["message"] == null)
            {
                var schedSC = db.ResourceSubCategories.Where(sc => sc.ResourceCategoryID == 8);
                ViewBag.ResourceSubcategory = new SelectList(schedSC, "Name", "Name");
                MonthsDropdown();
                YearDropDown();
                ViewBag.Message = "test";
                return View();
            }
            //29 is Schedules category, might need to make this morning dynamic in future
            else
            {
                var schedSC = db.ResourceSubCategories.Where(sc => sc.ResourceCategoryID == 8);
                ViewBag.ResourceSubcategory = new SelectList(schedSC, "Name", "Name");
                ViewBag.Message = TempData["message"];
                MonthsDropdown();
                YearDropDown();
                return View();
            }
        }

        // POST: Schedules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create([Bind(Include = "Year,IsActiveSchedule")] Schedule schedule, string ResourceSubcategory, string SchedMonth, string SchedYear)
        {
            string mimeType = Request.Files[0].ContentType;
            
            if (SchedMonth.Length == 0)
            {
                ModelState.AddModelError("Month", "Please select a month from the dropdown list.");
            }
            if (ResourceSubcategory.Length == 0)
            {
                ModelState.AddModelError("Resource", "Please select a category from the dropdown list.");
            }
            if (SchedYear.Length == 0)
            {
                ModelState.AddModelError("Year", "Please select a year from the dropdown list.");
            }
            if (!mimeType.Contains("image/jpeg"))
            {
                ModelState.AddModelError("Resource.FileStore.MimeType", "The schedule must be in JPEG format.");
            }
            
            
            if (ModelState.IsValid)
            {
                int y = Convert.ToInt32(SchedYear);
                var check = db.Schedules.Where(s => s.Month == SchedMonth & s.Year == y & s.Category == ResourceSubcategory & s.IsActiveSchedule == true).ToList();
                if (check.Count > 0)
                {
                    check[0].IsActiveSchedule = false;
                    db.Entry(check[0]).State = EntityState.Modified;
                }
                string fileName = Path.GetFileName(Request.Files[0].FileName);
                int fileLength = Request.Files[0].ContentLength;
                schedule.IsActiveSchedule = true;
                schedule.Category = ResourceSubcategory;
                schedule.Month = SchedMonth;
                schedule.Year = y;
                schedule.DataAdded = DateTime.Now;
                string schedDescript = ResourceSubcategory + ": " + @schedule.Month + " " + @schedule.Year;
                var subCat = db.ResourceSubCategories.Where(rsc => rsc.Name == ResourceSubcategory).Single();
                var resource = new Resource { FileDesc = schedDescript, DateAdded = DateTime.Now, ResourceCategoryID = 8, ResourceSubCategory = subCat };
                if (!(fileName == "" || fileLength == 0))
                {
                    Stream fileStream = Request.Files[0].InputStream;
                    byte[] fileData = new byte[fileLength];
                    fileStream.Read(fileData, 0, fileLength);
                    resource.FileStore = new FileStore
                    {
                        FileContent = fileData,
                        MimeType = mimeType,
                        FileName = fileName
                    };
                    db.Resources.Add(resource);
                    db.SaveChanges();
                    schedule.Resource = resource;
                };
                db.Schedules.Add(schedule);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ResourceID = new SelectList(db.Resources, "ID", "FileDesc", schedule.ResourceID);
            YearDropDown();
            MonthsDropdown();
            var schedSC = db.ResourceSubCategories.Where(sc => sc.ResourceCategoryID == 8);
            ViewBag.ResourceSubcategory = new SelectList(schedSC, "Name", "Name");
            return View(schedule);
        }

        // GET: Schedules/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            if (schedule.IsActiveSchedule)
            {
                
            }
            MonthsDropdown();
            YearDropDown(schedule.Year);
            ViewBag.ResourceID = new SelectList(db.Resources, "ID", "FileDesc", schedule.ResourceID);
            return View(schedule);
        }

        // POST: Schedules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit([Bind(Include = "ID,Category,Year,ResourceID,IsActiveSchedule")] Schedule schedule, string SchedMonth, string SchedYear)
        {
            if (SchedYear.Length == 0)
            {
                ModelState.AddModelError("Year", "Please select a year from the dropdown list.");
            }
            if (SchedMonth.Length == 0)
            {
                ModelState.AddModelError("Month", "Please select a month from the dropdown list.");
            }
            Schedule target = default(Schedule);
            

HospiceNiagara/Views/Schedules/Create.cshtml
@model HospiceNiagara.Models.Schedule

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2></h2>
<h2>Create</h2>

@using (Html.BeginForm("Create", "Schedules", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Schedule</h4>
        <hr />
        <div id="someDiv"></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.Month, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Month, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })
                </div>
            </div>*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Month, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SchedMonth", "Select a month")
                @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SchedYear", "Select a Year")
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.IsActiveSchedule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActiveSchedule, new { htmlAttributes = new { @class = "form-control", @action="CheckSchedule" } })
                @Html.ValidationMessageFor(model => model.IsActiveSchedule, "", new { @class = "text-danger" })
            </div>*@
        @*</div>*@
        <br />
        <div class="form-group">
            <label class="control-label col-md-2">Category</label>
            <div class="col-md-10">
                @Html.DropDownList("ResourceSubcategory", "Select a schedule type")
                @Html.ValidationMessageFor(model => model.Resource, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="FileUpload1">Attach File:</label>
            <div class="col-md-10">
                <input class="form-control" type="file" name="FileUpload1" />
                @Html.ValidationMessageFor(model => model.Resource.FileStore.MimeType, "", new { @class = "text-danger" })
                <br />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospiceNiagara/Views/Schedules/Delete.cshtml
@model HospiceNiagara.Models.Schedule

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Schedule</h4>
    <hr />
    <h4>@ViewBag.Warning</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Resource.FileDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resource.FileDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HospiceNiagara/Views/Schedules/Details.cshtml
@model HospiceNiagara.Models.Schedule

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Resource.FileDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resource.FileDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospiceNiagara/Views/Schedules/Edit.cshtml
@model HospiceNiagara.Models.Schedule

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Schedule</h4>
        <hr />
        <div id="someDiv"></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.ResourceID)
        @Html.HiddenFor(model => model.Category)
        @Html.HiddenFor(model => model.Year)
        @Html.HiddenFor(model => model.Month)
        <div class="form-group">
            @Html.LabelFor(model => model.Month, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SchedMonth", "Select a Month")
                @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SchedYear", "Select a Year")
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsActiveSchedule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActiveSchedule)
                @Html.ValidationMessageFor(model => model.IsActiveSchedule, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospiceNiagara/Views/Schedules/GoodIndex.cshtml
@*
    Priority:

    - P2 = Prototype 2
    - P3 = Prototype 3

    TO DO (COPY WHAT'S IN THE [ ] AND CTRL + F TO FIND THE SECTION):

    - Schedules [SCDL]: (P2) Hopefully we can get an import from outlook feature going for this area. Remember to include schedules three months ahead of time and three months previous.

    If you've finished one of these points, place a *DONE* at the beginning of the point.
*@

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*[SCDL]*@
<h2>Schedules</h2>
<button type="button" class="btn btn-link" data-toggle="modal" data-target="#modalSchedule">
    Add New Schedule
</button> 
<!-- Modal -->
<div class="modal fade" id="modalSchedule" tabindex="-1" role="dialog" aria-labelledby="myModalSchedule" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Add New Schedule</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="input-group">
                        <span class="input-group-addon" id="sizing-addon2">Title</span>
                        <input type="text" class="form-control" placeholder="Enter title here..." aria-describedby="sizing-addon2">
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="input-group col-lg-4">
                        <span class="input-group-addon" id="sizing-addon2">Year</span>
                        <input type="text" class="form-control" placeholder="Enter year here..." aria-describedby="sizing-addon2">
                    </div>
                    <div class="btn-group col-lg-2 col-lg-offset-0">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            Month <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">January</a></li>
                            <li><a href="#">February</a></li>
                            <li><a href="#">March</a></li>
                            <li><a href="#">April</a></li>
                            <li><a href="#">May</a></li>
                            <li><a href="#">June</a></li>
                            <li><a href="#">July</a></li>
                            <li><a href="#">August</a></li>
                            <li><a href="#">September</a></li>
                            <li><a href="#">October</a></li>
                            <li><a href="#">November</a></li>
                            <li><a href="#">December</a></li>
                        </ul>
                    </div>
                </div>
                <br />
                <div class="row">
                    <button type="button" class="btn btn-default">Upload Calendar</button>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default">Add</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<br />
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
                <a data-toggle="collapse" class="collapsed" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Welcome Desk Schedule
                </a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        February 2015 <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">February 2015</a></li>
                        <li><a href="#">March 2015</a></li>
                        <li><a href="#">April 2015</a></li>
                        <li class="divider"></li>
                        <li><a href="#">January 2015</a></li>
                        <li><a href="#">December 2014</a></li>
                    </ul>
                </div>
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingTwo">
            <h4 class="panel-title">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Residential Schedule
                </a>
            </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
            <div class="panel-body">
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        February 2015 <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">February 2015</a></li>
                        <li><a href="#">March 2015</a></li>
                        <li><a href="#">April 2015</a></li>
                        <li class="divider"></li>
                        <li><a href="#">January 2015</a></li>
                        <li><a href="#">December 2014</a></li>
                    </ul>
                </div>
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingThree">
            <h4 class="panel-title">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Pet Therapy
                </a>
            </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
            <div class="panel-body">
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        February 2015 <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">February 2015</a></li>
                        <li><a href="#">March 2015</a></li>
                        <li><a href="#">April 2015</a></li>
                        <li class="divider"></li>
                        <li><a href="#">January 2015</a></li>
                        <li><a href="#">December 2014</a></li>
                    </ul>
                </div>
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
            </div>
        </div>
    </div>
</div>

HospiceNiagara/Views/Schedules/Index.cshtml
@model IEnumerable<HospiceNiagara.Models.Schedule>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Schedules</h2>
@if (User.IsInRole("Administrator"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

@Html.DropDownList("ResidentialDD", null, "Residential", htmlAttributes: new { @class = "sel-sched" })
@Html.DropDownList("PetDD", null, "Pet Therapy", htmlAttributes: new { @class = "sel-sched" })
@Html.DropDownList("DayDD", null, "Welland Day Hospice", htmlAttributes: new { @class = "sel-sched" })
@Html.DropDownList("EventDD",null, "Event", htmlAttributes: new { @class = "sel-sched" })<br />
<a id="showLink">Show/Hide All</a>
<table class="table" id="showTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Resource.FileDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Month)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
       
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (!User.IsInRole("Administrator") & !item.IsActiveSchedule)
        {
            continue;
        }
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Resource.FileDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Month)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
           
            <td>
                @if (User.IsInRole("Administrator"))
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }); @:|
                }
                
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @if (User.IsInRole("Administrator"))
                {
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })@:|
                }

                @*@Html.ActionLink("Show", "ShowSched", new { id = item.ResourceID })*@
                @Ajax.ActionLink("Show", "ShowSched", new { id = item.Resource.FileStoreID }, new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "Get", UpdateTargetId = "someDiv" }, new {@class="show"})
                
            </td>
        </tr>
    }
</table>
<div id="someDiv">
   
</div>


@*@if (ViewBag.Mime == "image/jpeg")
    {
    <div>
        <img src="data:@ViewBag.Mime;base64,@ViewBag.FileBits" alt="@ViewBag.Name" width="600" height="400" />
    </div>
    }
    else
    {
    <div>no skedoole</div>
    }*@

HospiceNiagara/Views/Schedules/ScheduleCheck.cshtml
@model IEnumerable<HospiceNiagara.Models.Schedule>


<div>Warning: There is already an active @ViewBag.Category for @ViewBag.Month @ViewBag.Year. Continue with this opeation to make this the active schedule.</div>

HospiceNiagara/Views/Schedules/ScheduleEditCheck.cshtml
@model IEnumerable<HospiceNiagara.Models.Schedule>

<div>@ViewBag.Warning</div>

HospiceNiagara/Views/Schedules/ShowSched.cshtml
@model IEnumerable<HospiceNiagara.Models.Schedule>

<h3>@ViewBag.Title</h3>
    @if (ViewBag.Mime == "image/jpeg")
    {
        <div>
            <img src="data:@ViewBag.Mime;base64,@ViewBag.FileBits" alt="@ViewBag.Name" width="600" height="400" />
            
        </div>
        
    }