HospiceNiagara/Controllers/MeetingsController.cs
using HospiceNiagara.DAL;
using HospiceNiagara.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using HospiceNiagara.HospiceUserExtensions;

namespace HospiceNiagara.Controllers
{
    [Authorize]
    public class MeetingsController : Controller
    {
       
        enum Domains { Volunteer = 1, Staff = 2, Board = 3, Organizational = 4 };
        private HospiceNiagaraContext db = new HospiceNiagaraContext();
        // GET: Meetings
        [SessionTracking.Logging]
        public ActionResult Index(bool? newUser)
        {
            
            var invites = db.Invitations.ToList();
            var events = db.Events.ToList();
            var elists = new List<EventListViewModel>();
            //Administrator index of all events
            if (User.IsInRole("Administrator"))
            {
                var contacts = db.Contacts.ToList();
                foreach (var item in events)
                {
                    string count = (invites.Where(i => i.RSVP == true).Where(i => i.EventMeetingID == item.ID)).Count().ToString();
                    var newHosDate = new EventListViewModel { ID = item.ID, Name = item.Name, Location = item.Location, StartDate = item.StartDateTime, EndDate = item.EndDateTime, AttendanceCount = count};
                    string baseType = item.GetType().BaseType.ToString();
                    string type = baseType.Remove(0, "HospiceNiagara.Models.".Length);
                    newHosDate.Type = type;
                    elists.Add(newHosDate);
                }
                ViewBag.EventsList = elists;
            }
            //Invitation index for any user

            int contactID = User.GetHospiceContact().ID;
            if (contactID != null)
            {
                var singleInvites = new List<UserInviteViewModel>();
                var eventIDs = invites.Where(i => i.ContactID == contactID).ToList();
                foreach (var invite in eventIDs)
                {
                    var oneInvite = events.Where(e => e.ID == invite.EventMeetingID).Single();
                    var userInvite = new UserInviteViewModel { EventID = invite.ID, InviteID = invite.ID, Name = oneInvite.Name, StartDate = oneInvite.StartDateTime, EndDate = oneInvite.EndDateTime };
                    if (invite.RSVP == true)
                    {
                        userInvite.Attend = "Attending";
                    }
                    else if (invite.RSVP == false & invite.HasResponded == false)
                    {
                        userInvite.Attend = "RSVP";
                    }
                    else if (invite.RSVP == false & invite.HasResponded == true)
                    {
                        userInvite.Attend = "Not Attending";
                    }
                    singleInvites.Add(userInvite);
                }
                ViewBag.UserInvitesList = singleInvites;
            }
            if (newUser.HasValue)
            {
                if (newUser.Value)
                {
                    int team = User.GetHospiceContact().TeamDomainID;
                    string teamName = ((Domains)team).ToString();
                    string clickHere = "This is the meeting and events page. This page will display events and meetings that you have been asked to attend. On the right hand side you will see an RSVP button. Clicking on that will allow you to RSVP for a particular event or meeting.";
                    ViewBag.NewUserMessage = clickHere;
                }
            }
            return View(elists);
        }
        [HttpPost]
        public void AttendResponse(int inviteID, string attend)
        {
            var invitation = db.Invitations.Where(i => i.ID == inviteID).Single();
            if (attend == "Attending")
            {
                invitation.RSVP = true;
            }
            else if (attend == "Not Attending")
            {
                invitation.RSVP = false;
            }
            if (invitation.HasResponded == false)
            {
                invitation.HasResponded = true;
            }
            db.SaveChanges();
        }
        public ActionResult LoadDropDown(int? dID, string cIDs = "")
        {
            List<int> choosen = new List<int>();
            List<int> choosenDomains = new List<int>();
            string[] contactID = cIDs.Split(new string[] { "," }, StringSplitOptions.None);
            if (cIDs != "All")
            {
                foreach (string s in contactID)
                {
                    int num;
                    if (int.TryParse(s, out num))
                    {
                        choosen.Add(num);
                    }
                    else
                    {
                        if (s != "")
                        {
                            Domains d = (Domains)Enum.Parse(typeof(Domains), s);
                            choosenDomains.Add((int)d);
                        }
                    }
                }
                if (choosen.Count == 0)
                {
                    choosen.Add(0);
                }
                if (dID > 0)
                {

                    if (choosenDomains.Contains((int)dID))
                    {
                        var temp = db.Contacts.Where(c => c.TeamDomainID == dID & !choosen.Contains(c.ID));
                        ViewBag.ContactDD = new MultiSelectList(temp.Where(c => !choosenDomains.Contains(c.TeamDomainID)).ToList(), "ID", "FullName");
                    }
                    else
                    {
                        ViewBag.ContactDD = new MultiSelectList(db.Contacts.Where(c => c.TeamDomainID == dID & !choosen.Contains(c.ID)).ToList(), "ID", "FullName");
                    }

                    return PartialView("ContactDropDown");
                }
                else
                {
                    ViewBag.ContactDD = new MultiSelectList(db.Contacts.Where(c => !choosenDomains.Contains(c.TeamDomainID) & !choosen.Contains(c.ID)).ToList(), "ID", "FullName");
                    return PartialView("ContactDropDown");
                }
            }
            else
            {
                ViewBag.ContactDD = new MultiSelectList(Enumerable.Empty<SelectListItem>());
                return PartialView("ContactDropDown");
            }
        }

        public ActionResult CreateEvent()
        {
            return View();
        }
        public ActionResult CreateMeeting()
        {
            ViewBag.ContactsAddID = new SelectList(db.TeamDomains, "ID", "Description");
            ViewBag.ChoosenID = new SelectList(Enumerable.Empty<SelectListItem>());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMeeting([Bind(Include = "ID,Name,Date,StartDateTime,EndDateTime,Location,Requirements,Notes,StaffLead")] Meeting @meet, FormCollection fc)
        {
            //invitations
            //var valueProvider = fc.ToValueProvider();
            //foreach (var val in fc.Keys)
            //{
            //    string test = fc[val.ToString()];
            //}
            
            //Not dynamic, but useful way to handle pre-defined model uploads
            //pass current model instance and the name of the input file type control
            
            MeetingResource ag = new MeetingResource();
            MeetingResource att = new MeetingResource();
            MeetingResource min = new MeetingResource();
            try
            {
                ag.ResourceID = FileToEventResource(meet, "AgendaUpload", "AgendaID");
                att.ResourceID = FileToEventResource(meet, "AttendanceUpload", "AttendanceID");
                min.ResourceID = FileToEventResource(meet, "MinutesUpload", "MinutesID");
            }
            catch
            {
                return View("CreateMeeting");
            }
            var fileKeys = Request.Files.AllKeys;
            string ids = fc["ChoosenID"];
            if (ids != null)
            {
                List<int> choosen = new List<int>();
                List<int> choosenDomains = new List<int>();
                string[] contactID = ids.Split(new string[] { "," }, StringSplitOptions.None);
                foreach (string s in contactID)
                {
                    int num = 0;
                    if (int.TryParse(s, out num))
                    {
                        choosen.Add(num);
                    }
                    else
                    {
                        if (s != "")
                        {
                            if (s == "All")
                            {
                                choosenDomains.Add(0);
                            }
                            else
                            {
                                Domains d = (Domains)Enum.Parse(typeof(Domains), s);
                                choosenDomains.Add((int)d);
                            }
                        }
                    }
                }

                List<Contact> invites;
                //if (choosen.Count > 0)
                //{
                if (choosenDomains.Contains(0))
                {
                    invites = db.Contacts.ToList();
                }
                else
                {
                    invites = db.Contacts.Where(i => choosenDomains.Contains(i.TeamDomainID) | choosen.Contains(i.ID)).ToList();
                }
                //}
                //if (ContactsAddID != null)
                //{
                //    invites = db.Contacts.Where(c => c.TeamDomainID == ContactsAddID).Select(c => c).ToList();
                //}
                //else
                //{
                //    invites = db.Contacts.ToList();
                //}

HospiceNiagara/Views/Meetings/ContactDropDown.cshtml
<label class="control-label col-md-2">Choose Contacts</label>
<div class="col-md-10">
    @Html.DropDownList("ChooseList", (MultiSelectList)ViewBag.ContactDD,"All Contacts", htmlAttributes: new { @class = "form-control", @multiple = "multiple" })
    <a id="add">Add</a>
</div>

HospiceNiagara/Views/Meetings/CreateMeeting.cshtml
@model HospiceNiagara.Models.Meeting

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("CreateMeeting", "Meetings", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Meeting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Requirements, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Requirements, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Requirements, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StaffLead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StaffLead, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StaffLead, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4>Invitations</h4>
        <div class="form-group">
            <label class="control-label col-md-2">Team to add</label>
            <div class="col-md-10">
                @Html.DropDownList("ContactsAddID", null, "All Teams", htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group" id="someDiv">

        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Current invitations</label>
            <div class="col-md-10">
                @Html.DropDownList("ChoosenID", null, htmlAttributes: new { @class = "form-control", @multiple = "multiple" })
                <a id="remove">Remove</a>
            </div>
        </div>
        <h4>Add Resources</h4>
        @*Add listbox to input selected contacts from the above listbox using jquery, then submit this listbox on submit.
            Also needs an intersection table...I think*@
        @*<h5>Upload Agenda</h5>*@
        @*For now this item will just be categorized under Organizational/TestAgenda*@

        <div class="form-group">
            <label class="control-label col-md-2" for="AgendaUpload">Agenda:</label>
            <div class="col-md-10">
                <input class="form-control" type="file" name="AgendaUpload" /><br />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MinutesUpload">Minutes:</label>
            <div class="col-md-10">
                <input class="form-control" type="file" name="MinutesUpload" /><br />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="AttendanceUpload">Attendance:</label>
            <div class="col-md-10">
                <input class="form-control" type="file" name="AttendanceUpload" /><br />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default " />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospiceNiagara/Views/Meetings/Delete.cshtml
@model HospiceNiagara.Models.Event

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brochure.FileDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brochure.FileDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VolunteersNeeded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteersNeeded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Requirements)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Requirements)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StaffLead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StaffLead)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HospiceNiagara/Views/Meetings/Edit.cshtml
@model HospiceNiagara.Models.Event

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Meeting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VolunteersNeeded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VolunteersNeeded)
                    @Html.ValidationMessageFor(model => model.VolunteersNeeded, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Requirements, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Requirements, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Requirements, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StaffLead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StaffLead, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StaffLead, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospiceNiagara/Views/Meetings/EditEvent.cshtml
@model HospiceNiagara.Models.Event

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Event</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Meeting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VolunteersNeeded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VolunteersNeeded)
                    @Html.ValidationMessageFor(model => model.VolunteersNeeded, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Requirements, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Requirements, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Requirements, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StaffLead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StaffLead, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StaffLead, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospiceNiagara/Views/Meetings/EditMeeting.cshtml
  @model HospiceNiagara.Models.EditMeetingViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Meeting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Requirements, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Requirements, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Requirements, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StaffLead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StaffLead, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StaffLead, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="AgendaUpload">Agenda:</label>
            @if (Model.Agenda != "")
            {
                @Model.Agenda
            }
            else
            {
                <div class="col-md-10">
                    <input class="form-control" type="file" name="AgendaUpload" /><br />
                </div>
            }
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MinutesUpload">Minutes:</label>
            @if (Model.Minutes != "")
            {
                <div class="col-md-10">
                    @Model.Minutes
                </div>
            }
            else
            {
                <div class="col-md-10">
                    <input class="form-control" type="file" name="MinutesUpload" /><br />
                </div>
            }
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="AttendanceUpload">Attendance:</label>
            @if (Model.Attendance != "")
            {
                <div class="col-md-10">
                    @Model.Attendance
                </div>
            }
            else
            {
                <div class="col-md-10">
                    <input class="form-control" type="file" name="AttendanceUpload" /><br />
                </div>
            }
         </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>