HospiceNiagara/Models/BoardMember.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HospiceNiagara.Models
{
    public class BoardMember
    {
        public int ID { get; set; }

        [Required]
        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [Required]
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [Required]
        public string Position { get; set; }

        [Required]
        [DisplayName("Email")]
        public string EmailAddress { get; set; }

        [Required]
        [DisplayName("Home Address")]
        public string HomeAddress { get; set; }

        [Required]
        [DisplayName("Business Address")]
        public string BusinessAddress { get; set; }

        [Required]
        [MaxLength(10)]
        [DisplayName("Home Phone")]
        public string HomePhone { get; set; }
        
        [Required]
        [MaxLength(10)]
        [DisplayName("Business Phone")]
        public string BusinessPhone { get; set; }

        [Required]
        [MaxLength(10)]
        public string Fax { get; set; }

        [Required]
        [DisplayName("Partner Name")]
        public string PartnerName { get; set; }

        public List<string> BoardList { get; set; }
    }
}

HospiceNiagara/Controllers/BoardMembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospiceNiagara.DAL;
using HospiceNiagara.Models;

namespace HospiceNiagara.Controllers
{
    [Authorize]
    public class BoardMembersController : Controller
    {
        private HospiceNiagaraContext db = new HospiceNiagaraContext();

        // GET: BoardMembers
        [Authorize(Roles = "CantGetHere")]
        public ActionResult Index()
        {
            return View(db.BoardMembers.ToList());
        }

        public PartialViewResult BoardMemberList()
        {

                 var directors = db.BoardMembers.AsEnumerable();
                 ViewBag.Directors = directors;
                 return PartialView();
    
        }

        public ActionResult SearchResults(string SearchString)
        {
            
            if (!String.IsNullOrEmpty(SearchString))
            {
                var directors = db.BoardMembers.Where(d => d.LastName.ToUpper().Contains(SearchString.ToUpper())
                                       || d.FirstName.ToUpper().Contains(SearchString.ToUpper()));
                ViewBag.Directors = directors;
                return PartialView();
            }
            else
            {
                return null;
            }
            
        }

        // GET: BoardMembers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardMember boardMember = db.BoardMembers.Find(id);
            if (boardMember == null)
            {
                return HttpNotFound();
            }
            return View(boardMember);
        }

        // GET: BoardMembers/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BoardMembers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,Position,EmailAddress,HomeAddress,BusinessAddress,HomePhone,BusinessPhone,Fax,PartnerName")] BoardMember boardMember)
        {
            if (ModelState.IsValid)
            {
                db.BoardMembers.Add(boardMember);
                db.SaveChanges();
                return RedirectToAction("Index", "Contacts", new { area = "Index" });
            }

            return View(boardMember);
        }

        // GET: BoardMembers/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardMember boardMember = db.BoardMembers.Find(id);
            if (boardMember == null)
            {
                return HttpNotFound();
            }
            return View(boardMember);
        }

        // POST: BoardMembers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,Position,EmailAddress,HomeAddress,BusinessAddress,HomePhone,BusinessPhone,Fax,PartnerName")] BoardMember boardMember)
        {
            if (ModelState.IsValid)
            {
                db.Entry(boardMember).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Contacts", new { area = "Index" });
            }
            return View(boardMember);
        }

        // GET: BoardMembers/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoardMember boardMember = db.BoardMembers.Find(id);
            if (boardMember == null)
            {
                return HttpNotFound();
            }
            return View(boardMember);
        }

        // POST: BoardMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteConfirmed(int id)
        {
            BoardMember boardMember = db.BoardMembers.Find(id);
            db.BoardMembers.Remove(boardMember);
            db.SaveChanges();
            return RedirectToAction("Index", "Contacts", new { area = "Index" });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HospiceNiagara/Views/BoardMembers/BoardMemberList.cshtml
@model IEnumerable<HospiceNiagara.Models.BoardMember>


<h2>Board Of Directors</h2>

    <table>
        <tr>
            <td>Search Board Of Director Name: </td>
            <td>@Html.TextBox("SearchString", null, new { @class = "form-control", @id="txtSearch" })</td>
            <td></td>
            <td>@Ajax.ActionLink("Go", "SearchResults","BoardMembers" ,null, new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "Get", UpdateTargetId = "someDiv" }, new { @id = "search" }) @*@Html.ActionLink("Clear", "BoardMemberList")*@</td>
            
                @*<input type="submit" value="Filter" class="btn btn-default" />*@
                @*@Ajax.ActionLink("Show", "ShowSched", new { id = item.Resource.FileStoreID }, new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "Get", UpdateTargetId = "someDiv" }, new {@class="show"});*@
</tr>
    </table>
@Html.ActionLink("Clear", "Index")
@if (User.IsInRole("Administrator"))
{
    <p>
        @Html.ActionLink("Create New", "Create", "BoardMembers")
    </p>
}

<div id="someDiv">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HomeAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusinessAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HomePhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusinessPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fax)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartnerName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in ViewBag.Directors)
        {
            <tr>
                <td>
                    @item.FirstName
                </td>
                <td>
                    @item.LastName
                </td>
                <td>
                    @item.Position
                </td>
                <td>
                    @item.EmailAddress
                </td>
                <td>
                    @item.HomeAddress
                </td>
                <td>
                    @item.BusinessAddress
                </td>
                <td>
                    @item.HomePhone
                </td>
                <td>
                    @item.BusinessPhone
                </td>
                <td>
                    @item.Fax
                </td>
                <td>
                    @item.PartnerName
                </td>
                <td>
                    @if (User.IsInRole("Administrator"))
                    {
                        @Html.ActionLink("Edit", "Edit", "BoardMembers", new { id = item.ID }, null); @:|
                    }
                    
                    @Html.ActionLink("Details", "Details", "BoardMembers", new { id = item.ID }, null) |
                    @if (User.IsInRole("Administrator"))
                    {
                        @Html.ActionLink("Delete", "Delete", "BoardMembers", new { id = item.ID }, null)
                    }
                    
                </td>
            </tr>
        }

    </table>
</div>

HospiceNiagara/Views/BoardMembers/Create.cshtml
@model HospiceNiagara.Models.BoardMember

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BoardMember</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomeAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomeAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomeAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BusinessAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BusinessAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BusinessPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BusinessPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PartnerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartnerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartnerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospiceNiagara/Views/BoardMembers/Delete.cshtml
@model HospiceNiagara.Models.BoardMember

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BoardMember</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BusinessAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BusinessAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomePhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BusinessPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BusinessPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartnerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartnerName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HospiceNiagara/Views/BoardMembers/Details.cshtml
@model HospiceNiagara.Models.BoardMember

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BoardMember</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BusinessAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BusinessAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomePhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BusinessPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BusinessPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartnerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartnerName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospiceNiagara/Views/BoardMembers/Edit.cshtml
@model HospiceNiagara.Models.BoardMember

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BoardMember</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomeAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomeAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomeAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BusinessAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BusinessAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BusinessPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BusinessPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PartnerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartnerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartnerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospiceNiagara/Views/BoardMembers/Index.cshtml
@model IEnumerable<HospiceNiagara.Models.BoardMember>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HomeAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BusinessAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HomePhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BusinessPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fax)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PartnerName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HomeAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BusinessAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HomePhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BusinessPhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fax)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PartnerName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

HospiceNiagara/Views/BoardMembers/SearchResults.cshtml
@model IEnumerable<HospiceNiagara.Models.BoardMember>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HomeAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BusinessAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HomePhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BusinessPhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fax)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PartnerName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in ViewBag.Directors)
    {
        <tr>
            <td>
                @item.FirstName
            </td>
            <td>
                @item.LastName
            </td>
            <td>
                @item.Position
            </td>
            <td>
                @item.EmailAddress
            </td>
            <td>
                @item.HomeAddress
            </td>
            <td>
                @item.BusinessAddress
            </td>
            <td>
                @item.HomePhone
            </td>
            <td>
                @item.BusinessPhone
            </td>
            <td>
                @item.Fax
            </td>
            <td>
                @item.PartnerName
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "BoardMembers", new { id = item.ID }, null)|
                @Html.ActionLink("Details", "Details", "BoardMembers", new { id = item.ID }, null) |
                @Html.ActionLink("Delete", "Delete", "BoardMembers", new { id = item.ID }, null)
            </td>
        </tr>
    }

</table>